name: Pruebas JMeter

on:
  workflow_dispatch:
  push:
    paths:
      - "TestPlans/**.jmx"
      - ".github/workflows/jmeter.yml"

jobs:
  run-jmeter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create reports dir
        run: mkdir -p reports/html

      - name: Run JMeter test (PerfAction)
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: ./TestPlans/jsonplaceholder_prueba.jmx
          args: "-e -o ./reports/html/"

      - name: Upload JTL results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: result.jtl

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-report
          path: reports
