name: Pruebas JMeter

on:
  push:
    branches:
      - main

jobs:
  load_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run JMeter tests
        run: |
          jmeter -n -t TestPlans/jsonplaceholder_prueba.jmx.jmx -l resultados.jtl -e -o reportes

      - name: Upload JMeter test results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: test-results.jtl
